### ISSUE TITLE
Исправить.

### ISSUE THREAD

**Issue by air-breathing** [urfu-2015/team5#63]
- учесть при выводе списка квестов вошел в аккаунт пользователь или нет.
- при регистрации пользователя добавить его автоматический вход.
- верстка: 
  - выделение menu и main
  - footer и header в одном стиле
  - поправить лейбл
  - сделать общую стилистику inputs, buttons
  - если браузер старый, вывод соответсвующего сообщения
  - общие css свойства документа поправить
- реализовать поиск квестов

**Comment by michaeluskov** [comment]
А нужен ли нам IE8? 
Общая стилистика элементов и контролов у нас уже есть в bootstrap

**Comment by air-breathing** [comment]
На данный момент в ie 8 верстка валится. В примерах в документации у bootstrap есть базовый шаблон, указаны скрипты: response.js и еще какой-то. Но media queries, как написано, все равно не поддерживаются.
Есть 2 варианта: понять почему скрипты, которые должны были подключить работу media queries не работают. Либо нужный стили достать из media queries и отдельно в ie 8 их подключать.

**Comment by air-breathing** [comment]
Про необходимость поддержки старых браузеров можно много спорить, но если будет поддержка, то это лишь плюс. Единственное, я не знаю, как jquery работает с ie8. Работает ли..

**Comment by michaeluskov** [comment]
Предлагаю третий вариант: если детектируется старый браузер (IE<9), то перекидываем на какой-нибудь маршрут a la /badbrowser (как это делает вк). Поддерживать старые браузеры в проекте, котором это некритично (не бизнес-сектор, в котором тетя сидит на хр и не может поставить ничего, кроме ie8), не нужно, лучше наоборот подопнуть пользователя использовать что-то последнее.

**Comment by michaeluskov** [comment]
Jquery <2 работает

**Comment by air-breathing** [comment]
Да. В принципе ты прав.
